Work
unk9602753/module2 pull request #1
Opened 2022-05-20 02:36 UTC by unk9602753

2022-05-20 07:37 UTC, aryzhkou commented on build.gradle
> +group 'com.epam'
there must be application name as well https://maven.apache.org/guides/mini/guide-naming-conventions.html
 previously you had `esm` what was meaning of it?

2022-05-20 07:38 UTC, aryzhkou commented on build.gradle
> +        testImplementation 'com.h2database:h2:2.1.212'
group implementation,  testImplementation etc

2022-05-20 07:39 UTC, aryzhkou commented on controller/src/main/java/com/epam/esm/controller/ExceptionHandlerController.java
> +import static com.epam.esm.entity.ErrorCode.*;
never use wildcard import

2022-05-20 07:41 UTC, aryzhkou commented on controller/src/main/java/com/epam/esm/controller/ExceptionHandlerController.java
> +    public ResponseEntity<ResponseException> handleBadSqlGrammarException(BadSqlGrammarException e) {
please avoid ancient style of naming variables by one letter

2022-05-20 07:43 UTC, aryzhkou commented on controller/src/main/java/com/epam/esm/controller/ExceptionHandlerController.java
> +@ControllerAdvice
please have a look if there is difference with using RestControllerAdvice here

2022-05-20 07:46 UTC, aryzhkou commented on controller/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +                                                                 @RequestParam(value = "search_name", required = false, defaultValue = "") String name) {
I believe you can use search_name under the hood of search_criteria

2022-05-20 07:47 UTC, aryzhkou commented on controller/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +    public List<GiftCertificateDto> getAllCertificatesByCriteria(@RequestParam(value = "sort_direction", required = false, defaultValue = "asc") String direction,
if you have several sorting fields only one sort_direction won't be enough

2022-05-20 07:49 UTC, aryzhkou commented on controller/src/main/java/com/epam/esm/controller/TagController.java
> +    public ResponseEntity<Object> getTagById(@PathVariable long id) {
Why have you put @ResponseStatus everywhere except of getting by id?

2022-05-20 07:51 UTC, aryzhkou commented on controller/src/main/resources/messages.properties
> +
is it needed?

2022-05-20 07:53 UTC, aryzhkou commented on controller/src/main/resources/messages_ru.properties
> +ex.method.not.support=Метод не поддерживается
please use common style exception.*

2022-05-20 07:55 UTC, aryzhkou commented on dao/src/main/java/com/epam/esm/config/DaoConfig.java
> +        dataSource.setUrl(environment.getProperty("url"));
copypaste, again

2022-05-23 09:43 UTC, aryzhkou commented on controller/build.gradle
> +    implementation project(':dao')
please read about Layered Architecture

2022-05-23 09:46 UTC, aryzhkou commented on controller/src/main/java/com/epam/esm/config/WebConfig.java
> +        rs.setDefaultEncoding("UTF-8");
please use a constant from StandardCharsets

2022-05-23 09:55 UTC, aryzhkou commented on service/src/test/java/com/epam/esm/service/impl/TagServiceImplTest.java
> +    TagDao tagDao;
must be `private final`. Do you know why?

2022-05-23 09:57 UTC, aryzhkou commented on service/src/test/java/com/epam/esm/service/impl/TagServiceImplTest.java
> +        MockitoAnnotations.initMocks(this);
I believe in such versions of mockito you don't need that.

2022-05-23 09:58 UTC, aryzhkou commented on service/src/test/java/com/epam/esm/service/impl/TagServiceImplTest.java
> +    @BeforeEach
please add method
@AfterEach that will check that nomoreinteractions were occurred for your mocks

2022-05-24 08:25 UTC, unk9602753 commented on controller/build.gradle
> +    implementation project(':dao')
problem relate with name of modules?

2022-05-24 08:40 UTC, aryzhkou commented on controller/build.gradle
> +    implementation project(':dao')
no, the name is correct. dao should be used in service but not in controller. mixing layers are allowed in some cases but that won't lead to clear code.
https://cs.uwaterloo.ca/~m2nagapp/courses/CS446/1195/Arch_Design_Activity/Layered.pdf

2022-05-25 06:49 UTC, aryzhkou commented on dao/src/main/resources/dev-connection.properties
> +ps=5
bad code style naming

2022-05-25 06:51 UTC, aryzhkou commented on dao/src/test/java/com/epam/esm/dao/impl/GiftCertificateDaoImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
!

2022-05-25 06:53 UTC, aryzhkou commented on dao/src/test/java/com/epam/esm/dao/impl/TagDaoImplTest.java
> +@ActiveProfiles("dev")
remove it. you can simply run build without tests. write me here how it's possible

2022-05-25 06:56 UTC, aryzhkou commented on entity/src/main/java/com/epam/esm/exception/ServiceException.java
> +public class ServiceException extends RuntimeException {
why do you extend Runtime exception here?

2022-05-25 07:08 UTC, aryzhkou commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +            throw new ServiceException(ErrorCode.CODE_40001, id);
https://www.baeldung.com/java-checked-unchecked-exceptions#when

2022-06-28 13:40 UTC, aryzhkou commented on .gitignore
> +*/build/
I suppose just `build` will be enough

2022-06-28 14:04 UTC, aryzhkou commented on controller/src/main/java/com/epam/esm/config/WebConfig.java
> +        return lang == null || lang.isEmpty()
please verify if lang will be set as "  ".
also please confirm in case of smth like "incorrectlang" there will be corresponding message with error

2022-06-28 14:18 UTC, aryzhkou commented on dao/build.gradle
> +    systemProperty "spring.profiles.active","dev"
profiles must be set from environment variables or command line

2022-06-28 14:25 UTC, aryzhkou commented on dao/src/test/java/com/epam/esm/dao/impl/GiftCertificateDaoImplTest.java
> +@ActiveProfiles("dev")
tests can be avoided with corresponding gradle command (run without tests).
in case new environments will be set like _staging_ tests won't run and that will be the problem. please remove the profile here

2022-06-28 14:26 UTC, aryzhkou commented on dao/src/test/java/com/epam/esm/dao/impl/GiftCertificateDaoImplTest.java
> +    TagDao tagDao;
why default modifier?

2022-06-28 14:27 UTC, aryzhkou commented on dao/src/test/java/com/epam/esm/dao/impl/TagDaoImplTest.java
> +    GiftCertificateDao giftCertificateDao;
incapsulation principle ignorement

2022-06-28 14:28 UTC, aryzhkou commented on entity/build.gradle
> +dependencies {
please remove if not used

2022-06-28 14:30 UTC, aryzhkou commented on entity/src/main/java/com/epam/esm/entity/GiftCertificate.java
> +    public GiftCertificate(GiftCertificateDto giftCertificateDto) {
Why have you introduced this constructor instead of using builder?

2022-06-28 14:34 UTC, aryzhkou commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +            throw new ServiceException(ErrorCode.CODE_40003, id);
you could just check if giftCertificate was not presented and throw exception and otherwise do the rest logic instead of writing if-else

2022-06-28 14:35 UTC, aryzhkou commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        if (!(searchCriteria.equals("tag") || searchCriteria.equals("certificate"))) throw new ServiceException(ErrorCode.CODE_40021,searchCriteria);
rude ignoring code conventions principle

2022-06-28 14:40 UTC, aryzhkou commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        if (patch.getName() != null) {
please do all the checks on controller level and allow _service_ layer to concentrate on business logic

2022-06-29 07:06 UTC, aryzhkou commented on New Text Document.txt
> +rest
For what purpose is that file?

2022-06-29 07:07 UTC, aryzhkou commented on build.gradle
> +        implementation 'org.ostermiller:utils:1.07.00'
What's that?

2022-06-29 07:11 UTC, aryzhkou commented on controller/src/main/resources/messages_en.properties
> +
why so many blank lines?

2022-06-29 07:13 UTC, aryzhkou commented on dao/build.gradle
> +    systemProperty "spring.profiles.active","prod"
test must be possible to run against every environment, not prod only

2022-06-29 07:18 UTC, aryzhkou requested changes
* Too many unresolved comments
* Files `New Text Document.txt` and `Run` with unclear purpose
* copypaste
* commits must be clued into several by layers or incremental order

2022-08-03 17:20 UTC, merged